### ISSUE TITLE
Language flag does not work as intended

### ISSUE THREAD

**Issue by KennethEnevoldsen** [saattrupdan/ScandEval#35] opened 2022-06-06 12:03 UTC
When setting the language flag to DA the model still seems to be training on non-Danish datasets:

```
$ scandeval -m KennethEnevoldsen/dfm-bert-base  --language da
[...] 
↳ Finished finetuning and evaluation of KennethEnevoldsen/dfm-bert-base on DKHate.                                                               
[...]
↳ Benchmarking KennethEnevoldsen/dfm-bert-base on LCC:
[...]
↳ Benchmarking KennethEnevoldsen/dfm-bert-base on NoReC:
[...]
```

Scandeval version: 3.0.0

**Comment by saattrupdan** [comment] 2022-06-06 12:40
This is actually working as intended, as as described in the readme. Namely, the `language` argument only filters the models, not the dataset. So in your above script the `language` tag does nothing, as you've already specified a model.

That being said, there might be some value in filtering on datasets as well, but the question is how to present it in the API. We could filter on _both_ models and datasets, but then we lose the option of filtering on only of them. Maybe the solution is to have three tags:

- `language`, which filters on both models and datasets
- `model_language`, only filtering the models
- `dataset_language`, only filtering the datasets

**Comment by KennethEnevoldsen** [comment] 2022-06-06 14:06
Oh that is my bad. That sounds very reasonable.

So Danish models is all the models with the Danish tag og HF?

**Comment by saattrupdan** [comment] 2022-07-14 16:36
Fixed in [v4.0.0](https://github.com/saattrupdan/ScandEval/releases/tag/v4.0.0), via the separation of model languages (`-ml`) and dataset languages (`-dl`). If you only specify languages (`-l`) then this will cover both model and dataset languages.

**Closed by saattrupdan** 2022-07-14 16:36 UTC
Labels: enhancement

**Comment by usarth** [comment] 2024-09-08 16:17
But even when I set -dl nl the model seems to be finetuning,  is this a bug @saattrupdan ?
<img width="1246" alt="Screenshot 2024-09-08 at 18 16 42" src="https://github.com/user-attachments/assets/e98b6f2d-9106-4842-a608-d61e51bfa5c4">

**Comment by saattrupdan** [comment] 2024-09-09 05:50
@usarth Moved to a separate issue: https://github.com/ScandEval/ScandEval/issues/518
